spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/solardb
    username: postgres
    password: m0ng0l12p2trub0k
  flyway:
    baseline-on-migrate: true
    enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
