spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:{db-port}/{db-name}
    username: {user-name}
    password: {user-password}
  flyway:
    baseline-on-migrate: true
    enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
